# file: php5/tasks/configure.yml

- name: PHP5 | Update the php.ini
  template:
    src: etc_php5_apache2_php.ini.j2
    dest: /etc/php5/apache2/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
