# file: phpcommon/tasks/configure.yml

- name: PHP5 | Set up XDebug configuration (xdebug.ini)
  template:
    src: etc_php5_mods-available_xdebug.ini.j2
    dest: /etc/php5/mods-available/xdebug.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
