---
- hosts: all
  sudo: true
  vars:
    doc_root: /var/www
    sys_packages:
    - sendmail
    - nfs-common
    - nfs-kernel-server
    - portmap
    - git
    - imagemagick
    - openjdk-7-jdk
    - unzip
    - mailutils
    php_packages:
    - php5-mysql
    - php5-curl
    - php5-imagick
    - php5-gd
    - php-apc
    - php5-dev #needed for xdebug
    - php-pear #needed for xdebug
    - php5-xdebug
    php_ppa: php5-oldstable
  roles:
    - init
    - locale
    - apache
    - mysql
    - php5
    - phpcommon
